version: '4.54.0'

services:
  main-db:
    image: 'postgres'
    container_name: 'SDF_Final-main-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=04041996As!
      - POSTGRES_DB=SE_Final
    ports:
      - "2345:5432"

  test-db:
    image: 'postgres'
    container_name: 'SDF_Final-test-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=04041996As!
      - POSTGRES_DB=SE_Final_test
    ports:
      - "2346:5432"
