spring.application.name=SDF_Final

spring.datasource.url=jdbc:postgresql://localhost:5432/SE_Final
spring.datasource.username=postgres
spring.datasource.password=410228337

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.show-sql=true